### ISSUE TITLE
Responsed with "invalid_token"

### ISSUE THREAD

**Issue by Elessar116** [leVirve/dcard-spider#1]
Error occurred while setting number of posts as 100000000 to harvest the whole "Dcard Sex" forum.
![64612313](https://cloud.githubusercontent.com/assets/8136166/17141428/99291b2c-537e-11e6-981d-554a5fa21f4e.png)

This bug did not appear while executing the same command one more time.

**Comment by leVirve** [comment]
Tracked by https://github.com/leVirve/dcard-spider/commit/3d2366e93d8da4a34de2762b7f0a72c9b7efbae5
