### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by leeneil** [leVirve/dcard-spider#11]
不確定這樣改是不是最好的，不過 `Forum` 並不是一個 public 的 `class`，必須要透過 `dcard` 才拿的到

```
ariticle_metas = dcard.forums('funny').get_metas(num=Forum.infinite_page, sort='popular')
```

會報錯說不知道 `Forum` 是啥，暫時的 work around 是

```
ariticle_metas = dcard.forums('funny').get_metas(num=dcard.forums.infinite_page, sort='popular')
```

或許作者有更好的作法？

**Comment by leVirve** [comment]
我的想法是將 `Forum` 及 `Post` 兩個 class 都上提讓外部可以 `import` 這兩個類別，於是可以有下列兩種用法：

```python
import dcard

metas = dcard.Forum('funny').get_metas(num=dcard.Forum.infinite_page, sort='popular')
posts = dcard.Post(metas).get(comments=True)
```

```python
from dcard import Forum, Post

metas = Forum('funny').get_metas(num=Forum.infinite_page, sort='popular')
posts = Post(metas).get(comments=True)
```

或許這邊後續需要好好再重構了，謝謝你的建議！

**Comment by leeneil** [comment]
感謝您如此快速的回覆。坦白說我對 python 不是很熟悉，所以會有那樣的建議是我實際上嘗試

```
f = dcard.Forum()
```

或

```
from dcard import Forum
```

會得到錯誤，但是其實我也不曉得為什麼不能直接創一個 `Forum` 的實體。或許我說 `Forum` 不是 public 是錯的？

**Comment by leVirve** [comment]
嗨，是更新在這個 commit https://github.com/leVirve/dcard-spider/commit/588913a5a77e8035147192db429da09b75db4f97 的內容喔~ 
可以透過
```
pip install git+https://github.com/leVirve/dcard-spider
```
來重新安裝新版內容

**Comment by leeneil** [comment]
了解了解，我眼殘看錯地方了哈哈，想說 `dcard.py` 不是沒更新嗎XD
