### ISSUE TITLE
is it down?

### ISSUE THREAD

**Issue by wannafollowu** [leVirve/dcard-spider#14]
nothing is working
is it my computer problem or someone else can't work too?

**Comment by leVirve** [comment]
It seems like Dcard starts to blocked the requests from BOTs.
However, it can simply be bypass by adding fake user agent in the request header. I'll fix it if I'm free.

**Comment by wannafollowu** [comment]
sure, thanks for responding!
I've added the following codes in client.py
it seems to be fixed!

class Client:

    DEVICE_SETTINTS = {'manufacturer': 'Xiaomi',
                       'model': 'HM 1SW',
                       'android_version': 18,
                       'android_release': '4.3'}
    USER_AGENT = 'Dcard 6.8.10 Android ({android_version}/{android_release}; 320dpi; 720x1280; {manufacturer}; {model}; armani; qcom; en_US)'.format(**DEVICE_SETTINTS)

    def get_json(self, url, **kwargs):
        response = None
        self.session.headers.update ({'Connection' : 'close',
                                'Accept' : '*/*',
                                'Content-type' : 'application/x-www-form-urlencoded; charset=UTF-8',
                                'Cookie2' : '$Version=1',
                                'Accept-Language' : 'en-US',
                                'User-Agent' : self.USER_AGENT})

**Comment by leVirve** [comment]
Would this happen in each execution?
I have a quick fix on this with https://github.com/leVirve/dcard-spider/commit/09a9a7413b60d5437e47109baf83ee39a5de520d.
However, Dcard server sometimes returns HTTP 503 error. You can have more trials to check it.

**Comment by AnytimeRush** [comment]
how to download the pictures in comments by using command-line?
The parameters information in "dcard -h" didn't included the comments=True?
Thanks for the great tools.

**Comment by leVirve** [comment]
The later error is same as #15. Leave one thread for tracking.
