### ISSUE TITLE
Bug in file naming again

### ISSUE THREAD

**Issue by LordElessar** [leVirve/dcard-spider#2]
Error occurred several minutes after executing with "number of posts" as 100000000 the second time.
(harvesting pictures from "Dcard Sex" forum)

![2-1](https://cloud.githubusercontent.com/assets/8136166/17142255/072faaac-5382-11e6-9828-fa60131b3f07.png)
![2-2](https://cloud.githubusercontent.com/assets/8136166/17142157/ad16b89e-5381-11e6-9756-a1ee494cbbd4.png)
![2-3](https://cloud.githubusercontent.com/assets/8136166/17142161/af214ce4-5381-11e6-9c59-6768106eb2f0.png)

[dcard.log.txt](https://github.com/leVirve/dcard-spider/files/384087/dcard.log.txt)

Seems to be like a file name problem?

**Comment by leVirve** [comment]
This post has its title: `(圖)讀書中的小西斯\\('∀')` contains invalid characters for folder/filaname

**Comment by leVirve** [comment]
The char: `\` :-1: 
Filter fails in regex....

**Comment by leVirve** [comment]
caa48cb4ab4a7ee4b569e55d9ae2a04de83b

**Comment by leVirve** [comment]
close. More details, please refer be56baa48cb4ab4a7ee4b569e55d9ae2a04de83b

**Comment by leVirve** [comment]
closed

**Comment by leVirve** [comment]
closed
More details, please refer be56baa48cb4ab4a7ee4b569e55d9ae2a04de83b
