### ISSUE TITLE
json decode error

### ISSUE THREAD

**Issue by Elessar116** [leVirve/dcard-spider#6]
![bug](https://cloud.githubusercontent.com/assets/8136166/17455437/277db6da-5bea-11e6-8d84-fc05d667c06d.png)

**Comment by leVirve** [comment]
duplicate #4 

Seems still some problems there.

**Comment by leVirve** [comment]
These exceptions will be handled and logged. 
Ref: ://github.com/leVirve/dcard-spider/commit/99708acc20ba0d54f1d6499ddb166df294d83890

Next, make the request re-send or something.
