### ISSUE TITLE
沒有動作

### ISSUE THREAD

**Issue by zu030** [leVirve/dcard-spider#8]
你好，很感謝你的套件，但最近好像不能使用，有空的話，麻煩可以修正一下，感謝~

**Comment by Elessar116** [comment]
@zu030 看來是已經修正完成可以更新試試

**Comment by leVirve** [comment]
應該是 Dcard API parameter 略修改了
此次修正可參見 https://github.com/leVirve/dcard-spider/commit/471c48ffca8f860606561654cb7bba819c94b7fd

**Comment by zu030** [comment]
可以用了，感謝，辛苦了~
