### ISSUE TITLE
methods of forum do not work

### ISSUE THREAD

**Issue by amjltc295** [leVirve/dcard-spider#9]
I found that this package does not work.
I tried these codes:

```
forum = dcard.forums('funny')
forum.get_metas()
```
It returns nothing: [ ]
Also command lines:
```
dcard download --forum photography --number 100
```
It returns:
```
成功下載 0 items！
Finish in 0.20728 sec(s).
```

I use Python36 on Linux.
My code used to work two months ago.

**Comment by leVirve** [comment]
Hmm...after testing, these two methods work regularly.
- Functional API
```python
from dcard import Dcard

dcard = Dcard()
forum = dcard.forums('funny')
metas = forum.get_metas()
assert len(metas) == 30
```

- Command-line tool
```
$ dcard download --forum photography --number 30

成功下載 108 items！
Finish in 2.19640 sec(s).
```

Have you upgraded your `dcard-spider` yet? You can check it out by

```bash
dcard -V
```
The newest version now is `0.2.2`. Maybe you can upgrade the package, then try it again?

**Comment by amjltc295** [comment]
Thanks, you are right. I got the wrong version.
I used 
```
pip install dcard-spider --upgrade
```
It says that it its the latest version (0.2.13).
Why didn't it work?
I fixed the version problem by 
```
pip install "dcard-spider==0.2.2"
```

**Comment by leVirve** [comment]
Oh, I guess I know that problem: mislabel the version 😂 , `0.2.13` is greater than `0.2.2`...
It will be fixed after some coming refactors in newer version `0.3.0`.

**Comment by leVirve** [comment]
The release `0.3.0` is out!
